interface TextCalendarDictionary {
  [key: string]: string;
}

export enum Languages {
  ENGLISH = 'ENG',
  SPANISH = 'ESP',
  PORTUGUESE = 'POR',
}

export enum ErrorKeys {
  Required = 'required',
  MaxLength = 'maxlength',
  TitleRequired = 'titleRequired',
  TitleMaxLength = 'titleMaxLength',
  DescriptionMaxLength = 'descriptionMaxLength',
  DateFormatInvalid = 'dateFormatInvalid',
  StartDateRequired = 'startDateRequired',
  DateInvalid = 'dateInvalid',
  StartTimeRequired = 'startTimeRequired',
  TimeInvalid = 'timeInvalid',
  EndDateRequired = 'endDateRequired',
  EndDateInvalid = 'endDateInvalid',
  EndTimeRequired = 'endTimeRequired',
  EndDatePrevStartDate = 'endDatePrevStartDate',
  AddEventError = 'addEventError',
  UpdateEventError = 'updateEventError',
  DeleteEventError = 'deleteEventError',
  DeleteAllEventsOfTheDayError = 'deleteAllEventsOfTheDayError',
}

export enum PageElementsTextsKeys {
  DatePlaceHolderFormat = 'datePlaceHolderFormat',
  BtnGoToday = 'btnGoToday',
  BtnShowEvents = 'btnShowEvents',
  BtnHideEvents = 'btnHideEvents',
  BtnAddEvent = 'btnAddEvent',
  BtnNext = 'btnNext',
  BtnPrev = 'btnPrev',
  DeleteTitleDialog = 'deleteTitleDialog',
  DeleteMessageDialog = 'deleteMessageDialog',
  DeleteConfirmText = 'deleteConfirmText',
  DeleteCancelText = 'deleteCancelText',
}

export enum EventFormTextsKeys {
  HeaderTitleAdd = 'headerTitleAdd',
  HeaderTitleEdit = 'headerTitleEdit',
  Title = 'title',
  Description = 'description',
  StartDate = 'startDate',
  StartTime = 'startTime',
  EndDate = 'endDate',
  EndTime = 'endTime',
  Color = 'color',
  IsAllDay = 'isAllDay',
  BtnSaveText = 'btnSaveText',
  BtnCancelText = 'btnCancelText',
  BtnEditText = 'btnEditText',
  TimeModalTitle = 'timeModalTitle',
  MinutesText = 'minutesText',
  HourText = 'hourText',
}

export interface LanguageModel {
  fullMonthsNames: string[];
  shortMonthsNames: string[];
  fullDayNames: string[];
  shortDayNames: string[];
  pageElementsTexts: TextCalendarDictionary;
  errorMessages: TextCalendarDictionary;
  eventFormTexts: TextCalendarDictionary;
}

export const ENGLISH: LanguageModel = {
  fullMonthsNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  shortMonthsNames: [
    'Jan.',
    'Feb.',
    'Mar.',
    'Apr.',
    'May.',
    'Jun.',
    'Jul.',
    'Aug.',
    'Sep.',
    'Oct.',
    'Nov.',
    'Dec.',
  ],
  fullDayNames: [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ],
  shortDayNames: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  pageElementsTexts: {
    datePlaceHolderFormat: 'dd/mm/yyyy',
    btnGoToday: 'Today',
    btnShowEvents: 'Show events',
    btnHideEvents: 'Hide events',
    btnAddEvent: 'Add event',
    btnNext: 'Next',
    btnPrev: 'Prev',
    deleteTitleDialog: 'Delete event',
    deleteMessageDialog: 'Are you sure you want to delete this event?',
    deleteConfirmText: 'Delete',
    deleteCancelText: 'Cancel',
  },
  errorMessages: {
    titleRequired: 'Title is required',
    titleMaxLength: 'Title must be less than 60 characters',
    descriptionMaxLength: 'Description must be less than 200 characters',
    dateFormatInvalid: 'Date format is invalid',
    startDateRequired: 'Start date is required',
    dateInvalid: 'Date is invalid',
    startTimeRequired: 'Start time is required',
    timeInvalid: 'Time is invalid',
    endDateRequired: 'End date is required',
    endDateInvalid: 'End date must be equals or greater than start date',
    endTimeRequired: 'End time is required',
    endDatePrevStartDate: 'End date must be equals or greater than start',
    addEventError: 'Error adding event',
    updateEventError: 'Error updating event',
    deleteEventError: 'Error deleting event',
    deleteAllEventsOfTheDayError: 'Error deleting all events of the day',
  },
  eventFormTexts: {
    headerTitleAdd: 'Add event',
    headerTitleEdit: 'Edit event',
    title: 'Title',
    description: 'Description',
    startDate: 'Start date',
    startTime: 'Start time',
    endDate: 'End date',
    endTime: 'End time',
    color: 'Tag Color',
    isAllDay: 'All day',
    btnSaveText: 'Save',
    btnCancelText: 'Cancel',
    btnEditText: 'Edit',
    timeModalTitle: 'Select time',
    minutesText: 'Minutes',
    hourText: 'Hour',
  },
};

export const SPANISH: LanguageModel = {
  fullMonthsNames: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Deciembre',
  ],
  shortMonthsNames: [
    'Ene.',
    'Feb.',
    'Mar.',
    'Abr.',
    'May.',
    'Jun.',
    'Jul.',
    'Ago.',
    'Sep.',
    'Oct.',
    'Nov.',
    'Dec.',
  ],
  fullDayNames: [
    'Lunes',
    'Martes',
    'Miércoles',
    'Jueves',
    'Viernes',
    'Sábado',
    'Domingo',
  ],
  shortDayNames: ['Lun', 'Mar', 'Mié', 'Jue', 'Vir', 'Sáb', 'Dom'],
  pageElementsTexts: {
    datePlaceHolderFormat: 'dd/mm/aaaa',
    btnGoToday: 'Hoy',
    btnShowEvents: 'Mostrar eventos',
    btnHideEvents: 'Ocultar eventos',
    btnAddEvent: 'Agregar evento',
    btnNext: 'Siguiente',
    btnPrev: 'Anterior',
    deleteTitleDialog: 'Eliminar evento',
    deleteMessageDialog: '¿Está seguro que desea eliminar este evento?',
    deleteConfirmText: 'Eliminar',
    deleteCancelText: 'Cancelar',
  },
  errorMessages: {
    titleRequired: 'El título es obligatorio',
    titleMaxLength: 'El título debe tener menos de 60 caracteres',
    descriptionMaxLength: 'La descripción debe tener menos de 200 caracteres',
    dateFormatInvalid: 'El formato de fecha no es válido.',
    dateInvalid: 'La fecha no es válida',
    startDateRequired: 'La fecha de inicio es obligatoria',
    startTimeRequired: 'La hora de inicio es obligatoria',
    timeInvalid: 'La hora no es válida',
    endDateRequired: 'La fecha de fin es obligatoria',
    endDateInvalid: 'La fecha de fin debe ser igual o mayor a la de inicio',
    endTimeRequired: 'La hora de fin es obligatoria',
    endDatePrevStartDate:
      'La fecha de fin debe ser igual o mayor a la de inicio',
    addEventError: 'Error al agregar el evento',
    updateEventError: 'Error al actualizar el evento',
    deleteEventError: 'Error al eliminar el evento',
    deleteAllEventsOfTheDayError: 'Error al eliminar todos los eventos del día',
  },
  eventFormTexts: {
    headerTitleAdd: 'Agregar evento',
    headerTitleEdit: 'Editar evento',
    title: 'Título',
    description: 'Descripción',
    startDate: 'Fecha de inicio',
    startTime: 'Hora de inicio',
    endDate: 'Fecha de fin',
    endTime: 'Hora de fin',
    color: 'Color de etiqueta',
    isAllDay: 'Todo el día',
    btnSaveText: 'Guardar',
    btnCancelText: 'Cancelar',
    btnEditText: 'Editar',
    timeModalTitle: 'Seleccionar hora',
    minutesText: 'Minutos',
    hourText: 'Hora',
  },
};

export const PORTUGUESE: LanguageModel = {
  fullMonthsNames: [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julio',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Decembro',
  ],
  shortMonthsNames: [
    'Jan.',
    'Fev.',
    'Mar.',
    'Abr.',
    'Mai.',
    'Jun.',
    'Jul.',
    'Ago.',
    'Set.',
    'Out.',
    'Nov.',
    'Dec.',
  ],
  fullDayNames: [
    'Segunda',
    'Terça',
    'Quarta',
    'Quinta',
    'Sexta',
    'Sábado',
    'Domingo',
  ],
  shortDayNames: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
  pageElementsTexts: {
    datePlaceHolderFormat: 'dd/mm/aaaa',
    btnGoToday: 'Hoje',
    btnShowEvents: 'Mostrar eventos',
    btnHideEvents: 'Ocultar eventos',
    btnAddEvent: 'Adicionar evento',
    btnNext: 'Próximo',
    btnPrev: 'Anterior',
    deleteTitleDialog: 'Excluir evento',
    deleteMessageDialog: 'Tem certeza que deseja excluir este evento?',
    deleteConfirmText: 'Excluir',
    deleteCancelText: 'Cancelar',
  },
  errorMessages: {
    titleRequired: 'O título é obrigatório',
    titleMaxLength: 'O título deve ter menos de 60 caracteres',
    descriptionMaxLength: 'A descrição deve ter menos de 200 caracteres',
    dateFormatInvalid: 'O formato de data não é válido.',
    dateInvalid: 'A data não é válida',
    startDateRequired: 'A data de inicio é obrigatória',
    startTimeRequired: 'A hora de inicio é obrigatória',
    timeInvalid: 'A hora não é válida',
    endDateRequired: 'A data de fim é obrigatória',
    endDateInvalid: 'A data de fim deve ser igual o maior que a data de inicio',
    endTimeRequired: 'A hora de fim é obrigatória',
    endDatePrevStartDate:
      'A data de fim deve ser igual o maior que a data de inicio',
    addEventError: 'Erro ao adicionar evento',
    updateEventError: 'Erro ao atualizar evento',
    deleteEventError: 'Erro ao excluir evento',
    deleteAllEventsOfTheDayError: 'Erro ao excluir todos os eventos do dia',
  },
  eventFormTexts: {
    headerTitleAdd: 'Adicionar evento',
    headerTitleEdit: 'Editar evento',
    title: 'Título',
    description: 'Descrição',
    startDate: 'Data de inicio',
    startTime: 'Hora de inicio',
    endDate: 'Data de fim',
    endTime: 'Hora de fim',
    color: 'Cor da etiqueta',
    isAllDay: 'Todo o dia',
    btnSaveText: 'Salvar',
    btnCancelText: 'Cancelar',
    btnEditText: 'Editar',
    timeModalTitle: 'Selecionar hora',
    minutesText: 'Minutos',
    hourText: 'Hora',
  },
};

/**
 * Diccionario de idiomas.
 */
export const LANGUAGES: { [key in Languages]: LanguageModel } = {
  [Languages.ENGLISH]: ENGLISH,
  [Languages.SPANISH]: SPANISH,
  [Languages.PORTUGUESE]: PORTUGUESE,
};
